### PR TITLE
Set the sources index so that the sourcemap handles the file renaming appropriately to address issue #54

### LINKED ISSUE #54: Source-maps source path is wrong
when babeling a simple es6 file exactly like in the example,
the "sources" property of the ".map" file is it's name instead of path.

so if you have two files with the same name they will collide in the "sources" directory when debugging.

### PR DESCRIPTION
**Pull request by clarkmalmgren**
Fixes #54.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? Looks like something `applySourceMap` should handle.

**Comment by sindresorhus** [comment]
// @vzaidman @glen-84 @timjchin

**Comment by clarkmalmgren** [comment]
This might have also not actually solved the issue correctly.  I think I was a victim of my own caching.  I'll get back to you by EOD.

**Comment by clarkmalmgren** [comment]
So the problem is not in `applySourceMap` or in `replaceExt`.  the problem is that the `res.map.file` that is generated from `babel.transform` is turned into a flat file and the leading path is ignored.

**Comment by clarkmalmgren** [comment]
I should also note that the values in `fileOpts` appear to be correct.

**Pull request closed without merging**
