### PR TITLE
Added option to preserve source file name extensions.

### PR DESCRIPTION
**Pull request by nathanjd**
Added option to preserve source file name extensions. Added unit test and documentation for this new option. Changed variable name of `opts` to `options` to better reflect the readme.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Duplicate of #67.

**Comment by nathanjd** [comment]
Thanks! https://github.com/sindresorhus/gulp-revert-path looks like it will address my use case.

**Comment by AlastairTaft** [comment]
+1 On this issue, however the gulp plugin won't solve my use case. I'm using just standard npm scripts and the babel-cli to build my server side code. Didn't want to have to have the extra webpack dependency for server side, thought babel should be enough.

**Comment by jmm** [comment]
@AlastairTaft It sounds like you're not even using gulp?

**Comment by AlastairTaft** [comment]
Yeah, sorry, wrong place for me to report it. My solution wasn't even well though out either. If I'm using webpack client side I should also be using it server side else not much will work.

**Pull request closed without merging**
